---
title: My Resume
url: 'http://cgswong.github.io'
# Change it according to your repository name
baseurl: '/online-cv' 


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

# Profile information
name: 'Carrington Wong'
tagline: 'Solutions Architect / Infrastructure Engineer'
# Place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
pic: profile.png  

# Sidebar links
email: 'cgs.wong@gmail.com'
phone: '732 733 2367'
website: cgswong.github.io # Do not add http://
linkedin: 'cgswong'
github: 'cgswong'
twitter: '@cgswong'

# Tracker
analytics: UA-83979019-1
# Update all the sections by editing the files inside _includes folder.
